api_platform:
  defaults:
    item_operations: ['get']
    collection_operations: ['get']

  title: '达人共享宝 API 文档'
  #description: 'API 文档'
  version: '0.1.0'
  show_webby: false
  mapping:
    paths: ['%kernel.project_dir%/src/Entity']
  patch_formats:
    json: ['application/merge-patch+json']
  swagger:
    versions: [3]
  formats:
    json:
      mime_types: ['application/json']
    jsonld:
      mime_types: ['application/ld+json']
    html:
      mime_types: ['text/html']
  collection:
    pagination:
      items_per_page: 5 
      client_items_per_page: true
      items_per_page_parameter_name: itemsPerPage
