easy_admin:
  site_name: 达人共享宝
  formats:
    datetime: 'Y/m/d H:i'
  list:
    max_results: 50
  user:
    avatar_property_path: 'avatar'
  design:
    menu:
      - { entity: 'Task', icon: tasks }
      - { entity: 'Tag', icon: tags }
      - { entity: 'Category', icon: th-large }
      - { entity: 'Bid', icon: hand-paper }
      - { entity: 'Dividend', icon: gift }
      - { entity: 'LandTrade', icon: square }
      - { entity: 'LandPost', icon: square }
      - { entity: 'Equity', icon: bank }
      - { entity: 'Node', icon: file-text }
      - { entity: 'NodeType', icon: file-text }
      - { entity: 'User', icon: user }
      - { entity: 'Vip', icon: user-circle }
      - { entity: 'Level', icon: diamond }
      - { entity: 'Finance', icon: dollar }
      - { entity: 'Report', icon: flag }
      - { entity: 'Config', icon: cog }
    assets:
      favicon: '/img/favicon.ico'
      css:

  entities:
    NodeType:
      class: App\Entity\NodeType
      label: nodetype
    Task:
      class: App\Entity\Task
      label: task
      list:
        fields: 
          - id
          - title
          - price
          - prepaid
          - owner
          - platform
          - category
          - tag
          - quantity
          - applies
          - { property: 'approved', type: 'boolean'}
          - date
        filters: ['platform','category','tag','quantity']
      form:
        fields: 
          - name
          - title
          - price
          - { property: 'description', type: 'textarea'}
          - prepaid
          - owner
          - platform
          - category
          - tag
          - quantity
          - applies
          - showdays
          - approvedays
          - applydays
          - bidPosition
          - approved
        actions: ['-delete']
    Node:
      class: App\Entity\Node
      label: node
      help: 
      list: 
        filter: ['Title']
        fields:
          - id
          - title
          - type
          - body
          - up
          - down
          - date
          - author
      new: 
        fields:
          - title
          - type
          - { property: 'body', type: 'textarea'}
          - author
      edit:
        fields:
          - title
          - type
          - { property: 'body', type: 'textarea'}
          - up
          - down
          - date
          - author
      show:
      search:
    User:
      class: App\Entity\User
      label: user
      disabled_actions: ['show']
      list: 
        fields:
          - id
          - username
          - nick
          #- { property: 'avatar', label: 'avatar', type: 'avatar', is_image_url: 'true'}
          - phone
          - balanceTopup
          - balanceTask
          - gxb
        filters: ['roles']
      new: 
        fields:
          - username
          - { property: 'plainPassword', label: 'new.plainpass', type: 'text', type_options: { required: true } }
          - nick
          - { property: 'avatarFile', type: 'vich_image', label: 'avatar',  type_options: { allow_delete: false } }
          - phone
          - balanceTopup
          - balanceTask
          - gxb
      edit: 
        fields:
          - { property: 'username', type_options: { disabled: true, required: false } }
          - { property: 'plainPassword', label: 'edit.plainpass', type: 'text', type_options: { required: false } }
          - { property: 'avatarFile', type: 'vich_image', label: 'avatar',  type_options: { allow_delete: false } }
          - { property: 'nick', type_options: { required: false } }
          - { property: 'phone',  type_options: { required: false } }
    Tag:
      class: App\Entity\Tag
      label: tag
      list:
        title: '任务标签'
        fields: ['name']
      form:
        fields: ['name']
    Category:
      class: App\Entity\Category
      label: category
      disabled_actions: ['show']
      list:
        title: '任务类别'
        fields: ['name']
      form:
        fields: ['name']
    Vip:
      class: App\Entity\Vip
      label: vip
      list:
        fields: 
          - { property: 'uid', label: 'vip.uid'}
          - level
          - { property: 'date', label: 'vip.date'}
          - { property: 'days', label: 'vip.days'}
    LandTrade:
      class: App\Entity\LandTrade
      label: landtrade
      disabled_actions: ['new']
      list:
        title: '领地交易记录'
    LandPost:
      class: App\Entity\LandPost
      label: landpost
      disabled_actions: ['new']
      list:
        title: '领地广告'
    Bid:
      class: App\Entity\Bid
      label: bid
      disabled_actions: ['new']
      list:
        title: '竞价记录'
    Report:
      class: App\Entity\Report
      label: report
      disabled_actions: ['new']
      list:
        title: '举报记录'
    Finance:
      class: App\Entity\Finance
      label: finance
      disabled_actions: ['new']
      list:
        title: '财务明细'
    Equity:
      class: App\Entity\Equity
      label: equity
      disabled_actions: ['new']
      list:
        title: '股权交易记录'
    Dividend:
      class: App\Entity\Dividend
      label: dividend
      disabled_actions: ['new']
      list:
        title: '分红记录'
    Level:
      class: App\Entity\Level
      label: level
      list:
        fields: ['name','price','taskLeast','postFee','withdrawFee','stickyFee', 'Level.days']
        title: '会员等级'
    Config:
      class: App\Entity\Config
      label: config
      disabled_actions: ['new']
      list:
        fields: ['name','value']
        actions: ['-delete']
