easy_admin:
  site_name: 达人共享宝
  list:
    max_results: 50
  design:
    menu:
      - { entity: 'User', icon: user }
      - { entity: 'Node', icon: file-text }

  entities:
    Node:
      class: App\Entity\Node
      label: '文章'
      help: 
      list: 
        filter: ['Title']
      show:
      search:
    User:
      class: App\Entity\User
      icon: user
      label: '用户'
      list: 
        fields:
          - id
          - username
          - roles
