easy_admin:
  site_name: 达人共享宝
  list:
    max_results: 50
  design:
    menu:
      - { entity: 'Task', icon: tasks }
      - { entity: 'Tag', icon: tags }
      - { entity: 'Category', icon: th-large }
      - { entity: 'Bid', icon: hand-paper }
      - { entity: 'Dividend', icon: gift }
      - { entity: 'Land', icon: square }
      - { entity: 'Equity', icon: bank }
      - { entity: 'Node', icon: file-text }
      - { entity: 'User', icon: user }
      - { entity: 'Vip', icon: user-circle }
      - { entity: 'Level', icon: diamond }
      - { entity: 'Finance', icon: dollar }
      - { entity: 'Report', icon: flag }

  entities:
    Task:
      class: App\Entity\Task
      label: '任务'
      list:
        fields: ['id','name','title','price','prepaid','sticky','recommended','owner','platform','category','tag','quantity','applied']
        filters: ['sticky','recommended','platform','category','tag','quantity']
    Node:
      class: App\Entity\Node
      label: '话题'
      help: 
      list: 
        filter: ['Title']
      show:
      search:
    User:
      class: App\Entity\User
      label: '用户'
      list: 
        fields:
          - id
          - username
          - roles
        filters: ['roles']
    Tag:
      class: App\Entity\Tag
      label: '标签'
      list:
        fields: ['id','name']
    Vip:
      class: App\Entity\Vip
      label: '会员'
    Category:
      class: App\Entity\Category
      label: '类别'
      list:
        fields: ['id','name']
    Land:
      class: App\Entity\Land
      label: '领地'
    Bid:
      class: App\Entity\Bid
      label: '竞价'
    Report:
      class: App\Entity\Report
      label: '举报'
    Finance:
      class: App\Entity\Finance
      label: '财务'
    Equity:
      class: App\Entity\Equity
      label: '股权'
    Dividend:
      class: App\Entity\Dividend
      label: '分红'
    Level:
      class: App\Entity\Level
      label: '等级'
