easy_admin:
  site_name: 达人共享宝
  list:
    max_results: 50
  design:
    menu:
      - { entity: 'Task', icon: tasks }
      - { entity: 'Tag', icon: tags }
      - { entity: 'Category', icon: th-large }
      - { entity: 'Bid', icon: hand-paper }
      - { entity: 'Dividend', icon: gift }
      - { entity: 'Land', icon: square }
      - { entity: 'Equity', icon: bank }
      - { entity: 'Node', icon: file-text }
      - { entity: 'User', icon: user }
      - { entity: 'Vip', icon: user-circle }
      - { entity: 'Level', icon: diamond }
      - { entity: 'Finance', icon: dollar }
      - { entity: 'Report', icon: flag }
      - { entity: 'Config', icon: cog }
    assets:
      favicon: '/img/favicon.ico'
      css:

  entities:
    Task:
      class: App\Entity\Task
      label: '任务'
      list:
        fields: 
          - id
          - name
          - title
          - price
          - prepaid
          - sticky
          - recommended
          - owner
          - platform
          - category
          - tag
          - quantity
          - applied
        filters: ['sticky','recommended','platform','category','tag','quantity']
      form:
        fields: 
          - name
          - title
          - price
          - { property: 'description', type: 'textarea'}
          - prepaid
          - sticky
          - recommended
          - owner
          - platform
          - category
          - tag
          - quantity
          - applied
    Node:
      class: App\Entity\Node
      label: '话题'
      help: 
      list: 
        filter: ['Title']
      show:
      search:
    User:
      class: App\Entity\User
      label: '用户'
      list: 
        fields:
          - id
          - username
          - roles
        filters: ['roles']
    Tag:
      class: App\Entity\Tag
      label: '标签'
      list:
        title: '任务标签'
        fields: ['name']
      form:
        fields: ['name']
    Category:
      class: App\Entity\Category
      label: '类别'
      list:
        title: '任务类别'
        fields: ['name']
      form:
        fields: ['name']
    Vip:
      class: App\Entity\Vip
      label: '会员'
      list:
        fields: ['uid','level']
    Land:
      class: App\Entity\Land
      label: '领地'
      disabled_actions: ['new']
    Bid:
      class: App\Entity\Bid
      label: '竞价'
      disabled_actions: ['new']
    Report:
      class: App\Entity\Report
      label: '举报'
      disabled_actions: ['new']
      list:
        title: '举报记录'
    Finance:
      class: App\Entity\Finance
      label: '财务'
      disabled_actions: ['new']
      list:
        title: '财务明细'
    Equity:
      class: App\Entity\Equity
      label: '股权'
      disabled_actions: ['new']
    Dividend:
      class: App\Entity\Dividend
      label: '分红'
      disabled_actions: ['new']
    Level:
      class: App\Entity\Level
      label: '等级'
      list:
        fields: ['name','price','taskLeast','postFee','withdrawFee','stickyFee']
        title: '会员等级'
    Config:
      class: App\Entity\Config
      label: '设置'
      disabled_actions: ['new']
      list:
        fields: ['name','value']
