easy_admin:
  site_name: 达人共享宝
  list:
    max_results: 50

  entities:
    Node:
      class: App\Entity\Node
      label: '文章'
      help: 
      list: 
        filter: ['Title']
      show:
      search:
    User:
      class: App\Entity\User
      label: '用户'
