easy_admin:
  site_name: 达人共享宝
  list:
    max_results: 50
  design:
    menu:
      - { entity: 'Task', icon: tasks }
      - { entity: 'User', icon: user }
      - { entity: 'Tag', icon: tags }
      - { entity: 'Vip', icon: user-circle }
      - { entity: 'Category', icon: list }
      - { entity: 'Node', icon: file-text }

  entities:
    Node:
      class: App\Entity\Node
      label: '文章'
      help: 
      list: 
        filter: ['Title']
      show:
      search:
    User:
      class: App\Entity\User
      label: '用户'
      list: 
        fields:
          - id
          - username
          - roles
    Tag:
      class: App\Entity\Tag
      label: '标签'
    Task:
      class: App\Entity\Task
      label: '任务'
    Vip:
      class: App\Entity\Vip
      label: '会员'
    Category:
      class: App\Entity\Category
      label: '类别'
